### PR TITLE
showcase design improvement

### PR DESCRIPTION
**Pull request by Aluman**
Some design improvement on showcase-tactile. It doesn't require changes on activecell.

### CODE REVIEW

**Comment by adamrneary** [comment]
Why do we need to set this for every chart in the showcase, but none of the charts in activecell?

**Comment by Aluman** [comment]
If we will do common solution It affects to activecell. This way we can control showcase looks pretty and w/o any defects

**Comment by adamrneary** [comment]
but if it's needed for every chart, shouldn't it be the default? then we can override if specific charts need something different. it doesn't seem smart to have a configuration option that is needed for every chart...

**Comment by Aluman** [comment]
We don't change every chart, for example we did't change any charts which we used in activecell

**Pull request merged**
