### PR TITLE
145 smooth animation between stacked and grouped

### PR DESCRIPTION
**Pull request by Aluman**

### CODE REVIEW

**Comment by adamrneary** [comment]
i am looking at http://localhost:8000/#stacked-column and i am not seeing the change...

**Comment by adamrneary** [comment]
this PR should impact stacked-column and not include all the work on the aggregated functionality. that has its own issues that are separate.

**Comment by Aluman** [comment]
Fix animation for column renderer.

**Comment by adamrneary** [comment]
@Aluman this pull request is still polluted with stuff from other PRs. let's get a clean PR with just the work fixing this problem (please).

**Comment by dunice-mezencev** [comment]
@adamrneary We back to 'master' changes and implement it again.
**12** changed to length of display data

**Comment by adamrneary** [comment]
this is 99% there. it's animating too slowly. i think it might be because we're dividing the transition time by the length of the series and not the total number of dom objects to animate.

for example, if we had 72 months and 6 series, we would want to divide by 432, not 72. is that how it's set up currently?

**Pull request merged**
