### PR TITLE
Chart style guide and base styles for showcase References #34 References #66

### PR DESCRIPTION
**Pull request by ku5ic**

### CODE REVIEW

**Comment by ku5ic** [comment]
@adamrneary work in progress still, but I was thinking that you could have a clearer view of progress this a way.

**Comment by adamrneary** [comment]
word

**Comment by ku5ic** [comment]
@adamrneary I know you love me <3 :)

### Le preview

Tactile Bad ass interactive charts

**Comment by adamrneary** [comment]
Fantastic.

Only thing I can see from here is to pop the jquery alider out of the widget block.

But awesome!

Sent by iPhone

**Comment by ku5ic** [comment]
@adamrneary I'm afraid that LE js devs will have to move slider and stacked buttons out of the widget block. I've tried but with unsuccessful (terrifying) results

**Pull request merged**
