### PR TITLE
145 styling buttons

### PR DESCRIPTION
**Pull request by ku5ic**
## Le previews

Screen Shot 2013-04-29 at 18 08 10
Screen Shot 2013-04-29 at 18 07 28
Screen Shot 2013-04-29 at 18 08 23
Screen Shot 2013-04-29 at 18 07 54

cc le man @adamrneary

### CODE REVIEW

**Comment by adamrneary** [comment]
perfect.

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by ku5ic** [comment]
looking at it without header, you would not know if those screenshoots ware taken in the activecell app or from libraries ;) right @adamrneary?

and that's the point :)

**Comment by adamrneary** [comment]
is correct.

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by ku5ic** [comment]
:shipit: ?

**Pull request merged**
