### PR TITLE
Grid

### PR DESCRIPTION
**Pull request by Aluman**

### CODE REVIEW

**Comment by adamrneary** [comment]
the code looks fine, but where are we using this?

**Comment by adamrneary** [comment]
if this is for https://trello.com/card/when-there-are-negative-values-the-x-axis-should-be-visible/51adf65f9e42027c5e002d7c/80 i would want to avoid hard-coding grids into our charts all over the place. i think this code is fine, but let's also have it set so that if 0 isn't the top or bottom of the chart (but rather in the middle), then 1 horizontal line is included automatically.

**Comment by Aluman** [comment]
Ok. I can set a default value, or draw the line at all times.

**Comment by adamrneary** [comment]
by default: 
- [x] if 0 is not on the displayed y axis, no grid
- [x] if 0 is the top or bottom of the y axis, no grid
- [x] if 0 is somewhere in the middle of the y axis, display 1 horizontal line at 0

right?

**Comment by Aluman** [comment]
all clear, thanks

**Pull request merged**
