### PR TITLE
Fix bugs

### PR DESCRIPTION
**Pull request by Aluman**

### CODE REVIEW

**Comment by ksarna** [comment]
Leaderboard has stopped working correctly now. When you click set data labels are disappearing for a moment until reordering the list. On master, there's an animation of the numbers.

**Comment by adamrneary** [comment]
@Aluman now that i merged @ksarna's branch, this will probably need new assets.

**Comment by Aluman** [comment]
@adamrneary No leaderboard is broken, I fix it now.

**Comment by Aluman** [comment]
leaderboard example fixed

**Pull request merged**
