### PR TITLE
fix: clipped chart

### PR DESCRIPTION
**Pull request by Aluman**

### CODE REVIEW

**Comment by adamrneary** [comment]
couple screenshots? code looks good.

**Comment by Aluman** [comment]
before: before

after: after

**Comment by adamrneary** [comment]
cool. i presume if we bring over the new version of tactile.js into the app, this will fix the issues in the app without any changes to our views, yes?

**Comment by Aluman** [comment]
Yes, I've already created pull request https://github.com/activecell/activecell/pull/1003

**Pull request merged**
